<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'CoffeeCode\\Paginator\\' => array($vendorDir . '/coffeecode/paginator/src'),
    '' => array($baseDir . '/app'),
);
