<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit309ad19c190556cb22f8f84f97f2346e
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CoffeeCode\\Paginator\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CoffeeCode\\Paginator\\' => 
        array (
            0 => __DIR__ . '/..' . '/coffeecode/paginator/src',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/app',
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Slim' => 
            array (
                0 => __DIR__ . '/..' . '/slim/slim',
            ),
        ),
        'R' => 
        array (
            'Rain' => 
            array (
                0 => __DIR__ . '/..' . '/rain/raintpl/library',
            ),
        ),
    );

    public static $classMap = array (
        'EasyPeasyICS' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
        'PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
        'PHPMailerOAuth' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauth.php',
        'PHPMailerOAuthGoogle' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
        'POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.pop3.php',
        'SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.smtp.php',
        'ntlm_sasl_client_class' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
        'phpmailerException' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit309ad19c190556cb22f8f84f97f2346e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit309ad19c190556cb22f8f84f97f2346e::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInit309ad19c190556cb22f8f84f97f2346e::$fallbackDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit309ad19c190556cb22f8f84f97f2346e::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit309ad19c190556cb22f8f84f97f2346e::$classMap;

        }, null, ClassLoader::class);
    }
}
